- addons/Donate/integration/mcstock.php
I have changed the API action to get latest donations because get_sales was misleading. It's now changed to get_orders in the API.
> Changed API action for getting latest donations.

- pages/forum/view_topic.php
Fixed $p undefined when in the link is pointing to a specific post. Now you got a white page with only a error.
> Fix $p undefined when pointing to a specific post.

- pages/signin.php
I think debug for PHPMailer should be off, now anybody that has SMTP & 2FA enabled can see the communication between server & client. 
(This is my first Pull request, I'm not sure I'm doing it correct)
> Disable debug messages from the mail.

- pages/mod/reports.php
If a moderator clicked a report alert after it had been closed, the button to close the issue still appeared. This fixes that.
> Add a "report closed" label

- core/includes/template/footer.php
It was annoying me that the tachometer was clickable, so I was messing with it to make it not clickable but still show up correctly (cause if you remove href alltogher, the tachometer decides it doesnt wanna be in the right place anymore). I honestly came across this solution by accident when I typo'd, but hey, it works. Idk if its valid though. Feel free to send this to the trash can. Just something I liked having.
> Change tachometer function slightly

- README.md
- pages/admin/users.php
- styles/language/Czech/language.php
- styles/language/Dutch/language.php
- styles/language/EnglishUK/language.php
- styles/language/Finnish/language.php
- styles/language/French/language.php
- styles/language/German/language.php
- styles/language/Norsk/language.php
- styles/language/Portugues/language.php
- styles/language/Slovak/language.php
- styles/language/Spanish/language.php
If the user doesn't have an avatar at all, it won't display the button
If the user does have an enabled avatar, it gives the option to disable it
If the user doesn't have an enabled avatar but the file for one exists, it gives the option to enable it.
> Make the disable avatar button in the admin panel more intuitive

- pages/index.php
Needed to change line 193 to work with twitters new widget system. No need for widget ID's anymore, which causes the widget to not display in the side bar when enabled in the admin panel. Utilizes the twitter url for it's twitter feed.
> update to line 193

- pages/forum/view_topic.php
When you link to posts, the nav bar covers up a part of the reply panel.
This adds a bit of padding to the scroll so it shows up like this
> Change scroll destination

- pages/mod/applications.php
Currently, namelessmc is vulnerable that users who are in a group that can access the mod cp but aren't allowed to view staff applications don't see the link staff applications but can still browse them by simply going to /mod/applications. This adds the check that they can also view staff applications. If the user can't view staff apps, they cannot accept or deny either because view checks are made earlier.
Ps: dunno about the last no newline / newline edit. Github made that up
> Add checks if the user can view staff applications.

- README.md
I have had a bouncer on the channel for many months now and its shitposting and people asking questions then leaving 20 seconds later. Better to just point people to discord.
> Remove IRC from README because no one from the project uses it

- styles/language/EnglishUK/language.php
**What kind of issue is it (Question, Bug, etc.)?** Bug/Outdated Information.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.16.  
**How would you describe the issue?** The admin panel page (admin/minecraft) still says 'upcoming server plugin' on the hoverover text for 'Enable Nameless API'.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** Yes, I have the a screenshot of it. [Click here](http://i.imgur.com/LmbjGwc.png)  
**Do you have an idea how or where the issue occurs?** It occurs in the language file. Please see the pull request.
> Added link to NamelessPlugin Spigot Page

- custom/languages/Czech/general.php
- custom/languages/Dutch/general.php
- custom/languages/EnglishUK/general.php
- custom/languages/EnglishUS/general.php
- custom/languages/German/general.php
- custom/languages/Greek/general.php
- custom/languages/Japanese/general.php
- custom/languages/Norwegian/general.php
- custom/languages/Portuguese/general.php
- custom/languages/Romanian/general.php
- custom/languages/Slovak/general.php
- custom/languages/Spanish/general.php
- custom/languages/SwedishSE/general.php
- custom/templates/Default/contact.tpl
- modules/Core/pages/contact.php
This pull request implements an email field to the contact page #915. Validation is handled on the back end and new error messages have been created to handle an invalid email. These new fields have been added to all the language files so that they remain in sync. 
The email the user provides in the contact form is set in the "Reply To" header for emails sent through the php mail function. However, I could not figure out how to do this with the PHPMailer library so this still needs to be done. 
I have tested the front-end error handling and backend validation. However, I was not able to get email setup locally so this should still be tested.
> Add email field to contact form

- custom/panel_templates/Default/core/panel_templates.tpl
- modules/Core/pages/panel/panel_templates.php
Noticed today that the "View all templates" link for panel templates in my StaffCP just sent me to normal templates not panel templates. Thought I'd make a pull request rather than an issue for such a simple fix.
> Fixed "View all templates" link for specifically panel templates

- custom/templates/Default/header.tpl
If we are going to have support for the Open Graph protocol, then why not have support for Twitter cards?
> Add support for Twitter cards

- core/classes/Input.php
This activates the spell checker and changes the contextmenu of the editor to the browser contextmenu, allowing the words to be corrected with the browser's own dictionary.
> Browser-based spell checking for TinyMCE

- modules/Core/widgets/ProfilePostsWidget.php
The link for the last profile post was generated incorrectly because the author of the post was used in generating the profile post link.
> Fix latest profile posts link

- modules/Forum/classes/Forum.php
Topic URLs will now contain non-alphanumeric characters. For example, the [CJKV characters](https://en.wikipedia.org/wiki/CJK_characters).
- Fix #1683
In a past commit(https://github.com/NamelessMC/Nameless/commit/a50fb572181675f0686a54ad94a4e873e65889b4), non-alphanumeric characters were removed from the forum URL. I don't know the reason for this change, but if some reason exists, need to consider changing this Pull Request.
> Display non-alphanumeric characters in forum URLs

- modules/Forum/pages/forum/new_topic.php
Due to a coding mistake, the event was only fired when a webhook was configured for this forum. The code update will always fire the event.
> Make hook fire even if no hooks are there

- custom/languages/EnglishUK/admin.php
- custom/panel_templates/Default/core/debugging_and_maintenance.tpl
Add the ability to click a "here" text when the toaster pops up when the debug link is generated. This will ensure that people can always get the URL, even if the copying to their clipboard for some reason fails
> Add clickable link in toastr when requesting debug url

- error.php
- error.tpl
- modules/Core/queries/debug_link.php
This is to prevent any random from the internet from generating a debug link and getting all the debug data from your website.
> Add permission check to debug link query

- custom/templates/DefaultRevamp/css/custom.css
- custom/templates/DefaultRevamp/forum/view_topic.tpl
Old Group badges formating is way to big and looks really ugly when you have a group with a long name or your have a lot of groups.
That is my suggestion
> Froum Topic - Group Badges

- custom/panel_templates/Default/index.tpl
Server Compatibility  iocns on the left side
Looks way more clean.
**Before**
**After**
> Server Compatibility icons on the left side

- core/classes/Endpoints/EndpointBase.php
- core/classes/Endpoints/Endpoints.php
- custom/languages/EnglishUK/admin.php
- custom/panel_templates/Default/core/api_endpoints.tpl
- modules/Core/classes/Misc/Nameless2API.php
- modules/Core/includes/endpoints/GetUserEndpoint.php
- modules/Core/module.php
- modules/Core/pages/panel/api.php
API "route binding" is a feature which will allow us to simplify the DX of most of our API endpoints, especially simple GET ones.
- GET requests are ugly and annoying to debug
- Endpoints have to validate the params themselves
- To use variables passed to the endpoint, they are stored in a simple `<string, string>` array, with no real type checking.
- Example request: `https://example.com/api/users/ban?id=1`
- "Seamless" routes
- All param validation is done before the request is sent to an Endpoint class
- Params are passed as arguments to the `execute(Nameless2API $api, ...)` method in the Endpoint class, with type checking.
- Example request: `https://example.com/api/users/1/ban`
Given the second example request above:
- An Endpoint, in this case probably something called …
> API route binding

- core/classes/Core/Email.php
- custom/templates/DefaultRevamp/email/api_register.html
- custom/templates/DefaultRevamp/email/change_password.html
- custom/templates/DefaultRevamp/email/register.html
- custom/templates/DefaultRevamp/email/tfa.html
- modules/Core/includes/emails/register.php
- modules/Core/includes/endpoints/RegisterEndpoint.php
- modules/Core/pages/contact.php
- modules/Core/pages/forgot_password.php
- modules/Core/pages/panel/emails.php
- modules/Core/pages/panel/emails_errors.php
- modules/Core/pages/panel/emails_mass_message.php
- modules/Forum/pages/forum/view_topic.php
Instead of having a condition for sending mail over the `mail()` function vs PHPMailer, the class handles this on it's own now.
`Email::send(...)` now takes:
- array of "email" and "name" strings to determine the recipient
- string email subject
- string email message
- optional array of "email" and "name" strings to determine the reply-to address
`Email::addPlaceholder(...)` method for modules to add placeholders to their emails
> Emailing refactor!

- core/classes/Misc/CaptchaBase.php
- custom/languages/EnglishUK/admin.php
- modules/Core/classes/Captcha/Recaptcha2.php
- modules/Core/classes/Captcha/Recaptcha3.php
- modules/Core/classes/Captcha/hCaptcha.php
- modules/Core/pages/panel/registration.php
Altough this doesn't work for every single captcha type. It made more sense to have it for the ones that support it.
**hCaptcha**: 
**reCaptchaV2**:
**reCaptchaV3**:
This may not be ideal that it doesn't support everything but it does mean there is some protection in place to prevent people from activating captcha with invalid configurations.
> Verify captcha before allowing to save

- custom/panel_templates/Default/assets/css/custom.css
Fixed `hover` and `active` on the main nav. It was triggered even when dark mode was not active.
> Fixed `hover` and `active` on main nav

- core/classes/Avatars/AvatarSource.php
- core/classes/Collections/Collection.php
- core/classes/Collections/CollectionManager.php
- core/classes/Core/Input.php
- core/classes/Core/User.php
- core/classes/Core/Util.php
- core/classes/Misc/MentionsParser.php
- core/classes/Misc/Report.php
- modules/Core/includes/endpoints/ListUsersEndpoint.php
- modules/Core/module.php
- modules/Core/pages/leaderboards.php
- modules/Core/pages/panel/users_reports.php
- modules/Core/queries/mention_users.php
- modules/Core/queries/user.php
- modules/Forum/pages/forum/edit.php
- modules/Forum/pages/forum/new_topic.php
- modules/Forum/pages/forum/view_topic.php
https://user-images.githubusercontent.com/26070412/160975475-f199eaae-30c0-4712-9ea3-3f2267dc3527.mov
This also cleans up `MentionsParser` a tiny bit, and makes the `parse` method static.
Additionally, to avoid slowing down the user list endpoint, I had to rework how user avatars are generated so that I can use data already queried in the API endpoint to generate the avatars.
~~We might want to consider adding a `&like=<string>` GET query param to the user list endpoint, because if the suggestions take > 200ms to show up it will be super annoying for the users. @Derkades what are your thoughts on this?~~
~~Also, do you want to keep it as `.includes(...)` or would `.startsWith(...)` be better for showing suggestions?~~
~~- Currently it is using `includes`, which is fine for my dev site …
> Add mention suggestions in TinyMCE

- custom/templates/DefaultRevamp/css/custom.css
> Fixes the width for dropdowns when darkmode is enabled

- custom/panel_templates/Default/assets/css/custom.css
> Fix long dropdown names overflowing

- core/init.php
- core/templates/frontend_init.php
- custom/languages/en_UK.json
- custom/templates/DefaultRevamp/footer.tpl
Will close #2196 if approved.
If a user is logged out, and has language detection enabled (via a cookie), or if the cookie doesn't exist, then we attempt to get the browser locale and see if we have a matching language.
Not totally happy with "Auto language" as the button, so ideas are appreciated.
> (Optional) Auto language detection for guests

- package.json
- yarn.lock
select2: 4.0.0
Known security vulnerability: 1
Security advisory: 0
Exploits: unavailable
Highest severity: medium
Recommendation: 4.1.0-rc.0
Dependency Analytics Plugin [Powered by Snyk]
*From #2759*
> Remove vulnerability

- custom/panel_templates/Default/template.php
I'll be going through the admin panel to add more documentation links per the Discord discussion, and the method I've settled on requires a longer timeout to give users enough time to move their cursor onto hyperlinks. Example:
> Extend popover timeout

- core/classes/Database/QueryRecorder.php
- core/classes/Misc/Debugging.php
- core/classes/Misc/ErrorHandler.php
- core/init.php
- index.php
Bad title 😛 
This PR brings an optimization to the exception page.
Previously, when an exception is caught, the `ErrorHandler` class would go over the backtrace to make all of the frames + SQL query frames, even if the user could not view the detailed page.
Also, the `QueryRecorder` class would generate a frame on every SQL query, even if the user could not view the exception page.
This is because it was previously impossible for these classes to know if the user could view the page or not.
Now with the `Debugging` class which contains global booleans which are initialized according to the logged in user/guest/debugging state, these classes can check if the user can view the exception page or not, and skip doing certain tasks if not.
For example, the `QueryRecorder` will now skip …
> Global debugging constants to optimize requests when users cannot view exception page

- CHANGELOG.md
- core/classes/Group_Sync/GroupSyncManager.php
- core/classes/Integrations/IntegrationUser.php
- modules/Core/includes/endpoints/AddGroupsEndpoint.php
- modules/Core/includes/endpoints/RemoveGroupsEndpoint.php
- modules/Core/pages/panel/users_edit.php
- modules/Core/pages/panel/users_integrations.php
- modules/Discord Integration/classes/Discord.php
- modules/Discord Integration/classes/DiscordIntegration.php
working for me as expected,  the trade-off is that `"discord_role_id -> <role id>"` will be logged every time a group sync broadcast is made to their site logs, even if they already had the group
this *could* be avoided by two ways:
- not log any discord injector changes, meh
- group sync logging is a mess as it is. might be fine just removing the whole thing 🤔 
- making the bot return some nicer info when requests are made, such as whether the group was added/removed properly, or if they already had it/didn't have it
- this is probably the better option, but very annoying to implement.
waiting for some more testing from someone else, will merge/edit/rage-quit when i hear back from them
will close https://github.com/NamelessMC/Nameless/issues/2865
> group sync fixes:tm:

- core/classes/Core/Config.php
Fixes issue where friendly URLs, force HTTPS, force WWW were saving into config as `'1'` and `'0'` instead of `true` and `false`
> Fix non-string config values not saving properly

- modules/Core/classes/Misc/CoreApiErrors.php
The java API already used `unable_to_send_registration_email` so I don't consider this a breaking change (rather a *fixing* change?)
> Fix API error name

- core/classes/Core/Util.php
- modules/Core/pages/panel/modules.php
- modules/Core/pages/panel/panel_templates.php
- modules/Core/pages/panel/templates.php
Closes https://github.com/NamelessMC/Nameless/issues/2993
This adds a new method named `Util::isCompatible`, which determines if a module/template version is compatible with a given NamelessMC version.
For example:
- 2.0.1 and 2.0.2 are compatible
- 2.0.0 and 2.1.0 are incompatible
- 2.0.0 and 3.0.0 are incompatible
> Better module/template version check

- index.php
This is helpful for situations where the user claims their webserver is running 7.4+ but they are seeing this issue.
> Display PHP version in die() when version is not acceptable

- core/classes/Core/Language.php
Previously the `_activeLanguageFile` value would not be the exact language json path, instead it would replace the language short code with `__lng__.json`.
This caused issues on the email message editing page, since it could not find files named `custom/languages/__lng__.json`, etc.
This PR fixes this by setting the value to the actual path of the active language.
> Fix active language file value

- core/classes/Database/PhinxAdapter.php
Currently when a site is missing migrations, we [I] do three things that are not ideal:
- Throw an exception
- This is bad because it requires debugging mode to be enabled, or the user to be admin logged in, which means they often have to check the logs to even see the message
- Missing migrations are determined by just comparing the *size* of the `core/migrations` table and the `nl2_phinxlog` table
- This is not great because it does not consider the contents of them, and now that we have a new branch system, the likelihood of migrations being a little more messy in dev is much higher, so we should be stricter
- It does not say which migrations are missing
This change checks the file names and compares them to the phinxlog table contents, and prints the issues clearly in plain text so …
> Better missing/extra migration exception page

- core/templates/frontend_init.php
The error occurred when OAuth login was successful and it tried to redirect them to the previous page. Since "oauth" was not a page to be ignored while storing the `last_page` session variable, it would attempt to redirect it to the oauth.php file again, which threw the error since there was no provider in the URL params.
> Fix error showing when logging in with OAuth

- custom/templates/DefaultRevamp/js/core/core.js
- custom/templates/DefaultRevamp/js/core/pages.js
Honestly, when updating to Fomantic UI, with it it is a problem, because "The menu items need to have a referencing `data-tab` property and all missing tabs also a corresponding `tab segment`"
e.g.
```html
<div class="ui top attached tabular menu">
<a class="item active" data-tab="first">First</a>
<a class="item" data-tab="second">Second</a>
<a class="item" data-tab="third">Third</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="first">
First
</div>
<div class="ui bottom attached tab segment" data-tab="second">
Second
</div>
<div class="ui bottom attached tab segment" data-tab="third">
Third
</div>
```
But it is easier to just remove it.
"It makes more sense to fix it yeah but I doubt people will leave a bad review because of it" - @supercrafter100
> Remake tab initialization
