styles/language/German/language.php

translated everything to German (Du)

German translation added

---

core/classes/Cache.php
core/includes/template/footer.php
nginx.example
pages/install.php
pages/user/messaging.php

Removed htmlspecialchars from output, as the input has already been converted and this lead to "<b>hi</b>" for example, to be shown as "&lt;b&gt;hi..."

Nginx support, as well as improved install process with new error messages and support for the MySQL dependency.

---

pages/register.php
styles/language/EnglishUK/language.php
styles/language/German/language.php
styles/language/Spanish/language.php

Update German translation

---

styles/language/Spanish/language.php

Added some translations. Fixed typos.

Fixed spanish translation.

---

styles/templates/Default/forum_index_table.tpl

Move "Online Users" to a separate panel above latest posts

---

pages/forum/new_topic.php
pages/user/messaging.php

CloudFlare was causing these redirect pages to come up blank. The added tags prevent CloudFlare from caching the JavaScript, allowing the redirect to occur.

Fix JavaScript for CloudFlare

---

styles/language/Spanish/language.php

on Spanish Language have lite mistake
can't edit... to  can edit 
no puede editar a puedes editar

Lite Big Mistake... on Traslate

---

styles/language/Norsk/language.php

Added Norsk (Norwegian) language

Add Norsk (Norwegian) language 

---

pages/members.php

Change Members List avatar from always showing Minecraft avatar to showing a
custom avatar if the user has one.
(I have tested its much and working perfect) :P

Display custom avatars in Members List

---

pages/install.php

Like the commit title says because of 404 errors.

.php extensions removed from browser urls

---

ISSUE_TEMPLATE.md

**Note:** None of the content in the example section is real. It's just for demonstration purposes made.

An Issue template written with example.

---

pages/forum/edit_post.php

Added Cancel button when editing a post
**Note:** new_topic.php missing traslation on cancel button

Added Cancel button when editing a post

---

styles/language/Norsk/language.php

Updated Norsk Language

---

pages/admin/index.php

Error 404 benig caused for phpinfo

---

pages/user/messaging.php

Example me i pasted in a text and it was white text and page was white so it was hidden :/ and it was no options to edit the color

Allow people to use colors in private messages

---

styles/language/Dutch/language.php

Changed some lanugage strings for the Dutch file.

Some small changes to the Dutch lanugage file.

---

styles/language/Dutch/language.php

Changed: Bercith Titel -  To: Bericht Titel
Changed: Start - To:  Home (We dont use Start for homepages on dutch sites!)

Fixed some bad grammar

---

core/includes/getSelfURL.php
core/init.php
pages/forum/view_topic.php
styles/language/Czech/language.php
styles/language/Dutch/language.php
styles/language/EnglishUK/language.php
styles/language/Finnish/language.php
styles/language/French/language.php
styles/language/German/language.php
styles/language/Norsk/language.php
styles/language/Portugues/language.php
styles/language/Slovak/language.php
styles/language/Spanish/language.php

Added a option for the user to share the post(NOT REPLIES) to Facebook and Twitter.

Sharing on social media's 

---

pages/mod/reports.php

It wasn't working well so what I have do was just add white text

White Text for report section

---

styles/language/Portugues/language.php

Some little fixes. The language is now 100% with the last Nameless changes.

Little fixes

---

README.md

Add IRC info

---

pages/profile.php

Added Name History to see all players name changes
You can see how it looks here http://cubedcraft.com/profile/partydragen/
If you want to see a player who have changed name every time you can check out him http://cubedcraft.com/profile/Frozytime/

Added Name History list if you want it

---

core/includes/template/navbar.php
styles/language/Czech/language.php
styles/language/Dutch/language.php
styles/language/EnglishUK/language.php
styles/language/Finnish/language.php
styles/language/French/language.php
styles/language/German/language.php
styles/language/Norsk/language.php
styles/language/Portugues/language.php
styles/language/Slovak/language.php
styles/language/Spanish/language.php

Added Infractions to the pull down if admin logged in for easier access, also updated the language files for translation from various languages. 
Couldn't find a variable for if Infractions was enabled or not, so it just shows up all the time atm. Curious on if there is one and I'm just being an idiot and missing it.

added Infractions to pull down

---

ISSUE_TEMPLATE.md

Not that neccesary but it can help some people

We.re at 1.0.11

---

styles/language/Dutch/language.php

Translated some of the new things and corrected 2 translations

Dutch translations

---

styles/language/German/language.php

Finished German translation.

---

pages/admin/users.php
styles/language/Czech/language.php
styles/language/Dutch/language.php
styles/language/EnglishUK/language.php
styles/language/Finnish/language.php
styles/language/French/language.php
styles/language/German/language.php
styles/language/Norsk/language.php
styles/language/Portugues/language.php
styles/language/Slovak/language.php
styles/language/Spanish/language.php

Needs to add user_title to all languages but I only know English

Add Title to users in admin panel

---

pages/admin/pages.php

Allowed people doing "Well" in custom pages

Allowed people doing "Well" in custom pages

---

pages/profile.php

Added  ''Well'' in Wall posts, About, Name History

Added ''Well'' in Wall posts, About, Name History To profile.php

---

styles/templates/Default/forum_index_table.tpl

Looks a bit cleaner for forums that don't have subforums

Only show .panel-body with subforums if $parent.forums > 0

---

core/includes/getSelfURL.php

Removed https port because it would default back to it. Shorter for twitter.

Removed HTTPS Port

---

pages/profile.php

Its pointless. :x
Hopefully I've got this commit right, it's 3:30 AM. Anyone wanna double check for me?

Don't alert the user if they are posting on their own profile

---

README.md

Add webchat link

---

pages/admin/help.php
pages/admin/sidebar.php
styles/language/Czech/language.php
styles/language/Dutch/language.php
styles/language/EnglishUK/language.php
styles/language/Finnish/language.php
styles/language/French/language.php
styles/language/German/language.php
styles/language/Norsk/language.php
styles/language/Portugues/language.php
styles/language/Slovak/language.php
styles/language/Spanish/language.php

I see some other Softwares have a help page on admin panel so why not have it here too xD
So i created a simple page, Its may better to have a knowlegebase addon thats are planned on NamelessMC Website in v2
Then help page can load that page from NamelessMC to always display latest information/tutorials?
Its currently looks like this: http://imgur.com/a/GlA3d (without bakground)
(Its not using the language files its english only but all the urls is english so whatever

Added Help page

---

pages/forum/index.php

Fix for post counting, the old way also counted posts from deleted topics.

Update forum main posts

---

styles/language/German/language.php

I have translated some things and improved existing translations.

Language.php Update | German

---

styles/language/German/language.php

Fixed some mistakes :3

---

custom/languages/EnglishUS/EnglishUS/admin.php
custom/languages/EnglishUS/EnglishUS/errors.php
custom/languages/EnglishUS/EnglishUS/general.php
custom/languages/EnglishUS/EnglishUS/moderator.php
custom/languages/EnglishUS/EnglishUS/table.php
custom/languages/EnglishUS/EnglishUS/time.php
custom/languages/EnglishUS/EnglishUS/user.php
custom/languages/EnglishUS/EnglishUS/version.php
custom/languages/German/admin.php
custom/languages/German/errors.php
custom/languages/German/general.php
custom/languages/German/moderator.php
custom/languages/German/table.php
custom/languages/German/time.php
custom/languages/German/user.php
custom/languages/German/version.php
install.php

Credit Page, Translations GERMAN & EnglishUS

Credits Page, Translations

---

styles/language/Dutch/language.php

Removed and fixed some strange-formulated sentences, grammar-mistakes and other typo's

updated Dutch translation

---

pages/admin/forums.php

Remove extra line

---

custom/languages/Dutch/admin.php
custom/languages/Dutch/errors.php
custom/languages/Dutch/general.php
custom/languages/Dutch/moderator.php
custom/languages/Dutch/table.php
custom/languages/Dutch/time.php
custom/languages/Dutch/user.php
custom/languages/Dutch/version.php

Dutch translation for NamelessMC 2.0.0pre1
(Not done yet)

Added dutch translation

---

styles/language/Spanish/language.php

Spanish Language File is now 100% Finished :)

Spanish 100%

---

custom/languages/Dutch/user.php

Translated the Authme things

---

.htaccess

Made it a bit more efficient for the Options -Indexes by making it on 1 single line

Efficient way of using Options

---

custom/languages/Dutch/installer.php

Edited a few things so the grammar and syntax are correct

Edited a few things

---

custom/languages/Greek/admin.php
custom/languages/Greek/errors.php
custom/languages/Greek/general.php
custom/languages/Greek/installer.php
custom/languages/Greek/table.php
custom/languages/Greek/time.php
custom/languages/Greek/version.php

Added Greek Language for Admin.php. I will make small changes again. I will update the other files soon.

Added Greek Language for Admin

---

modules/Forum/language/French/language.php

add the french translation of the forum module !

French Forum language.php

---

addons/Donate/language-french.php
addons/Donate/language_french.php

Create language_french.php for French translation of vote addon

---

addons/Members/language_french.php

Create Members language_french.php

---

styles/language/Norsk/language.php

I went through and quickly edited most of the grammatical errors in the translation. It seems like the previous translation was pulled from Google Translate, making it annoying to read and sometimes hard to understand.
Some words are hard to find replacements for, perhaps others have better suggestions. 
I'm not too sure if I'm completely finished with this translation, but I think most errors are now fixed.
It would be great if another Norwegian could have a look at this and correct whichever errors I've placed.

Improved wording in the Norwegian translation

---

core/assets/css/cp_dark.css

card correction

---

custom/languages/Norwegian/general.php

Translated server query

---

README.md

This adds the credits for the wonderful people who made the official NamelessMC Discord bot! :)

Add NamelessBOT credits to contributor list.

---

pages/profile.php

I don't think I added any check if infractions is actually enabled so that might need to be added.

Integrate Infractions tab into Profile page

---

README.md

Add a link to my website via my name.

---

addons/BugReport/BugReport.php
addons/BugReport/initialisation.php
addons/BugReport/language.php
addons/BugReport/settings.php
pages/bugreport.php
pages/mod/bugreport.php

As requested at https://github.com/NamelessMC/Nameless/issues/534

Add Bug Report addon

---

custom/languages/Dutch/installer.php

Making it look more normal, also making some thing more understandable for non-tech persons!

Updating dutch language

---

custom/languages/Norwegian/general.php

Translated the contactform section

Translate contactform

---

pages/api/v1/index.php
pages/register.php
pages/signin.php

Fixed mail headers. (On php with msmtp sendmail and mail without MIME-Version and Content-type text will be striped and any url or long text will be affected.)
Reported here: https://github.com/NamelessMC/Nameless/issues/705

Fixed mail headers.

---

custom/languages/Romanian/admin.php
custom/languages/Romanian/user.php
modules/Forum/language/Romanian/forum.php

I cecked my translation file and i find missing terms, now all terms is up to date!

Adding missing terms

---

install.php

Don't repeat yourself

---

custom/languages/Czech/admin.php

Translated messages of the new additions: Secondary Groups, Deleting Templates and Discord ID.

Translated Secondary G., Deleting T., Discord ID

---

styles/language/Portugues/language.php

Signed-off-by: João Paulo <dasilvaj4@gmail.com>

Update "second group" string

---

custom/languages/Portuguese/admin.php
custom/languages/Portuguese/errors.php
custom/languages/Portuguese/general.php
custom/languages/Portuguese/installer.php
custom/languages/Portuguese/moderator.php
custom/languages/Portuguese/table.php
custom/languages/Portuguese/time.php
custom/languages/Portuguese/user.php
custom/languages/Portuguese/version.php

Signed-off-by: João Paulo <dasilvaj4@gmail.com>

Update same strings translations

---

.idea/Nameless.iml
.idea/modules.xml
pages/signin.php
styles/templates/Default/signin.tpl

You can easily accept this pull request if you want to swap the place and colors of the signin and register button as suggested in the Discord server.

Swap place and color of signin and register buttons

---

styles/language/German/language.php

Made small changes to the language file.

Small Changes from new and old lines

---

custom/languages/Dutch/user.php

I dont know where nickname is being used, so maybe that translation is going to be changed.

Translated the new added sentences to dutch

---

ISSUE_TEMPLATE.md

added two requests : 
one for modules list
the other for theme used
(Can help handling modules/theme linked problems)

Added requests

---

core/classes/Hash.php
pages/install.php

mcrypt is no longer needed stated by Samerton on Discord.

Removed Requirement of mcrypt

---

custom/languages/Spanish/admin.php

Updated a few translations (WIP)

---

custom/languages/Romanian/admin.php

Translation 100% complet.

---

modules/Core/widgets/DiscordWidget.php
modules/Core/widgets/FacebookWidget.php
modules/Core/widgets/TwitterWidget.php

WITH BR: https://i28.servimg.com/u/f28/17/31/96/85/screen18.png
WITHOUT BR: https://i28.servimg.com/u/f28/17/31/96/85/screen19.png
https://i28.servimg.com/u/f28/17/31/96/85/screen20.png

add one <be> on each social widget for esthetic reasons.

---

addons/Donate/integration/craftingstore.php
addons/Donate/sync.php

Updated the CraftingStore Integration to support API V4, this API uses header based auth instead of placing the API token in the URL, thus it's safer.
And changing category names resulted in double categories, it now uses name checking instead of ID checking to prevent this.

CraftingStore: Use new V4 API with header based auth.

---

custom/templates/Default/forum/new_topic.tpl

same as this: https://github.com/NamelessMC/Nameless/commit/ae4ceb1d775aa20dab6d065abd53c531075d6e15

fix display

---

core/init.php
custom/languages/Chinese/general.php
custom/languages/Czech/general.php
custom/languages/Dutch/general.php
custom/languages/EnglishUK/general.php
custom/languages/EnglishUS/general.php
custom/languages/German/general.php
custom/languages/Greek/general.php
custom/languages/Japanese/general.php
custom/languages/Norwegian/general.php
custom/languages/Portuguese/general.php
custom/languages/Romanian/general.php
custom/languages/Slovak/general.php
custom/languages/Spanish/general.php
custom/languages/SwedishSE/general.php

I removed the html from the language files and made the tooltip it's own message. 
In my opinion, it looks the best without an additional button around it. At least it did when I tried different buttons. 
resolves #1181

V2 click to copy IP

---

core/classes/Email.php

In the state so far, letters were wrong when sending mails in Japanese etc. I fixed it.

Fix...It corresponded to UTF-8.

---

custom/languages/German/admin.php
custom/languages/German/errors.php
custom/languages/German/general.php
custom/languages/German/installer.php
custom/languages/German/moderator.php
custom/languages/German/user.php

I have been updated some Messages from English to German

Updated German Language

---

index.php

fix rewrite_test in installer

---

addons/Donate/settings.php

it's time to end the confusion

Changed Buycraft to its new name

---

styles/language/EnglishUK/language.php

Removed MinecraftMarket and MCStocks; added CraftingStore

Rest in peace, Buycraft and MinecraftMarket

---

custom/languages/Czech/general.php

Translated untranslated messages to Czech

Translated general.php to Czech

---

custom/languages/Czech/moderator.php

Translated untranslated messages to Czech

Translated moderator.php to Czech

---

custom/languages/Czech/user.php

Translated untranslated messages and fixed mistakes in translation

Translated user.php to Czech

---

custom/languages/Czech/errors.php

Translated untranslated messages to Czech

Translated errors.php to Czech

---

custom/languages/Czech/api.php

Every single message translated to Czech

Translated api.php to Czech

---

custom/languages/Portuguese/installer.php

Translation updated and fixed errors.

All translated and updated

---

custom/languages/Portuguese/api.php

Completely translated to portuguese and revised older translations.

Fully translated api.php

---

custom/languages/Portuguese/general.php

Completely translated to portuguese and revised older translations.

Fully translated general.php

---

styles/language/French/language.php

Hi, I've done a correction on API Language. Because it wasn't complèté but complété.
:)

Correction on French Language

---

custom/languages/German/admin.php

Update german admin.php

---

custom/languages/German/user.php

- Added german translation
- Less formal
- No such thing as AGBs changed to AGB

Update german user.php

---

custom/languages/Czech/user.php

Fixed typos and translated some sentences (lol, why this even replaced my last translation that was fully translated without any typos)

Fixed translation

---

custom/languages/Czech/admin.php

Corrected some translations, translated untranslated sentences from the "New" translation that was added.
Please, look at the old commit before the translation by Ethxrnity was added (It was fully translated there was no need to upload a file that wasn't even using the translation)

Corrected translation

---

custom/languages/Czech/api.php

Looks like someone made that file in bad encoding uwu

Translation changes and File Encoding fix (UTF-8)

---

custom/languages/Portuguese/user.php

Translation revised, corrected and translated.

Revised user.php

---

custom/languages/Portuguese/moderator.php

Translation revised, corrected and translated.

Revised moderator.php

---

core/classes/User.php

Fix accounts with special characters in name having no avatar

Fix names with special characters having no avatar

---

custom/languages/Czech/admin.php

Changed a few translations to make them more accurate!

Update of admin.php

---

modules/Forum/language/Chinese(Simplified)/forum.php

Chinese(Simplified) Translation for module forum
Most of its words have been Localized,Translated by ahdg

Chinese(Simplified) Translation for module forum

---

modules/Core/pages/validate.php

Success! Your account failed to validate.

Fix wrong type of alert on validation error

---

core/classes/Validate.php
custom/languages/Chinese(Simplified)/general.php
custom/languages/Chinese/general.php
custom/languages/Czech/general.php
custom/languages/Dutch/general.php
custom/languages/EnglishUK/general.php
custom/languages/EnglishUS/general.php
custom/languages/German/general.php
custom/languages/Greek/general.php
custom/languages/Italian/general.php
custom/languages/Japanese/general.php
custom/languages/Lithuanian/general.php
custom/languages/Norwegian/general.php
custom/languages/Polish/general.php
custom/languages/Portuguese/general.php
custom/languages/Romanian/general.php
custom/languages/Slovak/general.php
custom/languages/Spanish/general.php
custom/languages/SpanishES/general.php
custom/languages/SwedishSE/general.php
custom/languages/Turkish/general.php
modules/Core/pages/register.php
modules/Core/pages/user/settings.php

Thanks KFD for pointing this out

Add backend validation for emails and timezones

---

custom/languages/Chinese(Simplified)/admin.php
custom/languages/Chinese(Simplified)/api.php
custom/languages/Chinese(Simplified)/user.php

Chinese (Simplified) translations

---

core/installation/views/steps/admin_account_setup.php
core/installation/views/steps/database_configuration.php
core/installation/views/steps/general_configuration.php
core/installation/views/steps/site_configuration.php
docker-compose.yaml

Speeds up installation for development environments (see docker-compose file) and my hosting website.
Closes #1886

Installer defaults from environment variables

---

custom/panel_templates/Default/integrations/discord/discord.tpl
modules/Core/pages/panel/discord.php

im stupid and didnt change branches

bot url readonly - now handled by Nameless Link

---

custom/panel_templates/Default/includes/update.tpl

Fix update alert styling

---

custom/languages/Dutch/admin.php

I translated the Favicon, Logo and some Discord Bot errors.

Translated Favicon, logo & some Discord Bot Errors

---

modules/Forum/language/Portuguese/forum.php

Hello, I did the complete translation for the latest (beta) version currently available, I hope you like it and integrate it into the project.

Update forum.php portuguese translation

---

modules/Core/includes/endpoints/CreateReportEndpoint.php

Bug fix in issue #2077 
Post test screen: [Imgur](https://imgur.com/KyiPyah)

Fixed bug in isssue#2077

---

core/classes/DB.php

Helps solve problem with default MySQL connect encoding and utf8mb4

add charset option to PDO dsn

---

core/classes/CaptchaBase.php
core/includes/updates/200-pr9.php
custom/panel_templates/Default/core/registration.tpl
custom/templates/DefaultRevamp/contact.tpl
custom/templates/DefaultRevamp/login.tpl
custom/templates/DefaultRevamp/register.tpl
modules/Core/classes/Recaptcha2.php
modules/Core/classes/Recaptcha3.php
modules/Core/classes/hCaptcha.php
modules/Core/init.php
modules/Core/module.php
modules/Core/pages/contact.php
modules/Core/pages/login.php
modules/Core/pages/panel/registration.php
modules/Core/pages/register.php

Rework captcha system and add Recaptcha 3

---

modules/Forum/pages/forum/view_topic.php

This fixes a bug I came across a while ago. 
If a reply was deleted and it was the last reply it would show a strange page, this fixes that issue

Fixed issue with pagination

---

core/classes/User.php
core/classes/Util.php
modules/Core/pages/panel/avatars.php

Crafthead is a new(ish), super fast avatar service made by Tux - the Velocity proxy maintainer.

Add support for Crafthead avatar service

---

custom/templates/DefaultRevamp/js/core/core.js
custom/templates/DefaultRevamp/register.tpl
modules/Core/pages/register.php

Closed previous PR due to issue with commits

Added feature of receiving timezone on registration

---

custom/languages/Japanese/admin.php
custom/languages/Japanese/api.php
custom/languages/Japanese/emails.php
custom/languages/Japanese/errors.php
custom/languages/Japanese/general.php
custom/languages/Japanese/installer.php
custom/languages/Japanese/log.php
custom/languages/Japanese/moderator.php
custom/languages/Japanese/table.php
custom/languages/Japanese/time.php
custom/languages/Japanese/user.php
custom/languages/Japanese/version.php
modules/Forum/language/Japanese/forum.php

All Japanese translations have been updated to NamelessMC 2.0.0-pr9.
**Update**
```
custom/languages/Japanese/admin.php
custom/languages/Japanese/api.php
custom/languages/Japanese/emails.php
custom/languages/Japanese/errors.php
custom/languages/Japanese/general.php
custom/languages/Japanese/installer.php
custom/languages/Japanese/log.php
custom/languages/Japanese/moderator.php
custom/languages/Japanese/user.php
custom/languages/Japanese/version.php
modules/Forum/language/Japanese/forum.php
```

Update japanese translations.

---

core/includes/smarty/debug.tpl

design modern

---

custom/templates/DefaultRevamp/user/new_message.tpl

Added default recipient value

---

custom/languages/Slovak/admin.php
custom/languages/Slovak/api.php
custom/languages/Slovak/emails.php
custom/languages/Slovak/errors.php
custom/languages/Slovak/general.php
custom/languages/Slovak/installer.php
custom/languages/Slovak/moderator.php
custom/languages/Slovak/table.php
custom/languages/Slovak/time.php
custom/languages/Slovak/user.php
custom/languages/Slovak/version.php
modules/Forum/language/Slovak/forum.php

Synchronized with EnglishUK using Crowdin.

Update Slovak translation

---

modules/Forum/language/SpanishES/forum.php

Full translation from "EnglishUK". Made from scratch

Missing translation in SpanishES

---

custom/panel_templates/Default/assets/css/custom.css
custom/panel_templates/Default/sidebar.tpl

Possible temporary fix to #2328
If there's any way to align the icons and text in the overflow  too, please make that edit.

possible fix to #2328

---

core/installation/views/steps/upgrade.php

In this step, the password was displayed clear text on the screen.
In this PR I change the field type to password so that the input is hidden.

Change DB password field to password type

---

core/classes/TemplateBase.php

This fixes a stylesheet having both a rel="stylesheet" and rel="preload" when using rel="preload".

Fix duplicate rel="..." when using rel="preload"

---

custom/panel_templates/Default/assets/css/custom.css

Fix some spacing, organize things better, add dark mode variables to make changing dark mode colors easier in the future, remove unneeded semicolons. Nothing has been removed except some old code that was commented out that I accidentally left from when I developed this, just re-organized.
Note: **UNTESTED,** you would have to test before merging. I cannot test atm because I am at school.

Custom CSS Revamp

---

custom/languages/Polish/user.php

just wondering, do you guys participate in Hacktoberfest?

Update Polish Language

---

core/classes/Events/EventHandler.php

Create the ability to get the event data like listeners, params, etc by using the `EventHandler::getEvent()` function. This allows us to see additional info and make for easier working with the event system

Add ability to get event data

---

modules/Core/pages/panel/profile_fields.php

Better Redirect for Edit Profile Fields page

Better Redirect for Edit Profile Fields page

---

custom/panel_templates/Default/assets/css/custom.css

Fixed 'card-header' dark mode color
Fixed navbar color for dark mode

Dark Mode Color Fix

---

modules/Forum/language/Turkish/forum.php

`can_edit_topic` was missing in the turkish translation file. Dunno if that is the correct translation xD

Turkish Language fix for Forum

---

custom/panel_templates/Default/assets/css/custom.css
custom/panel_templates/Default/assets/js/sb-admin-2.js
custom/panel_templates/Default/footer.tpl

New bit smaller footer, better formating and new usefull links.
Old Footer:
New Footer
Darkmode

New Footer

---

custom/languages/Czech/admin.php
custom/languages/Czech/api.php

Update Czech language

---

core/assets/css/cp_dark.css
core/assets/css/custom.css
custom/panel_templates/Default/assets/css/custom.css

Better dark mode

---

custom/panel_templates/Default/core/hooks_new.tpl
custom/panel_templates/Default/core/profile_fields_create.tpl
custom/panel_templates/Default/core/registration.tpl
custom/panel_templates/Default/core/social_media.tpl
custom/panel_templates/Default/core/widgets/online_users.tpl
custom/panel_templates/Default/core/widgets_edit.tpl
custom/panel_templates/Default/forum/forums_edit.tpl
custom/panel_templates/Default/forum/forums_new_step_2.tpl
custom/panel_templates/Default/forum/forums_settings.tpl
custom/panel_templates/Default/integrations/discord/discord.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft_account_verification.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft_authme.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft_servers.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft_servers_edit.tpl
custom/panel_templates/Default/integrations/minecraft/minecraft_servers_new.tpl

Bye switchery teemo

---

core/classes/Endpoints/Endpoints.php
modules/Core/module.php

code is gross, will change this to the user integration system when #2606 is merged
examples:
```
/users/3
/users/id:3
/users/username:Aberdeener
/users/integration_name:minecraft:Derkades
/users/integration_id:discord:271510274475819008
/users/integration_name:discord:aberdeener#0001
```

Support looking up a user in the API many different ways

---

custom/panel_templates/Default/assets/css/custom.css
custom/panel_templates/Default/core/security_view.tpl

Panel template fixes

---

custom/panel_templates/Default/template.php

Topic placeholder editor fixed

---

core/classes/Core/Util.php
modules/Core/pages/panel/errors.php
modules/Core/queries/debug_link.php

Only read last part of error log

---

custom/panel_templates/Default/assets/css/custom.css
custom/panel_templates/Default/core/api.tpl
custom/panel_templates/Default/core/profile_fields_create.tpl
custom/panel_templates/Default/core/profile_fields_edit.tpl
custom/panel_templates/Default/index.tpl
custom/panel_templates/Default/integrations/discord/discord.tpl
custom/panel_templates/Default/integrations/minecraft/placeholders.tpl

Colors & wrong icon in StaffCP

---

custom/panel_templates/Default/assets/css/custom.css

So, instead of crushing my head with css, I did what SB Admin 2 does, is make the page longer instead of making sidebar scrollable.
https://user-images.githubusercontent.com/71085027/170672412-83910717-c21c-4a74-8bb9-799167263e45.mp4
*totally serious note: it took me 20 minutes*
Closes #2347

Fix sidebar for StaffCP

---

core/classes/Core/Util.php
core/init.php

Move Util::isModuleEnabled(...) before cache check

---

custom/templates/DefaultRevamp/css/custom.css

Small patch for the color

---

custom/panel_templates/Default/index.tpl

Make colors for statistics

---

custom/panel_templates/Default/assets/css/custom.css
custom/panel_templates/Default/index.tpl

Hide statistics on small devices

---

modules/Core/classes/Captcha/Recaptcha2.php
modules/Core/classes/Captcha/hCaptcha.php

Dark/light mode for Captcha

---

core/classes/Core/Config.php
core/classes/Core/URL.php
core/classes/Core/Util.php
core/classes/Database/DB.php
core/classes/Database/DatabaseInitialiser.php
core/classes/Database/QueryRecorder.php
core/classes/Misc/DebugBarHelper.php
core/classes/Misc/ErrorHandler.php
core/includes/updates/200-pr13.php
core/init.php
core/installation/steps/ajax_initialise.php
core/installation/steps/conversion_perform.php
core/installation/steps/database_configuration.php
core/installation/steps/finish.php
core/installation/steps/requirements_validation.php
core/installation/steps/upgrade.php
custom/languages/en_UK.json
index.php
install.php
modules/Core/pages/panel/general_settings.php
modules/Core/pages/panel/index.php
modules/Core/pages/panel/registration.php
modules/Core/queries/debug_link.php
modules/Core/widgets/ServerStatusWidget.php
scripts/cli_install.php
scripts/seeder/db_seeder.php

Also many random other fixes. This should hopefully prevent or at least reduce weird "config unavailable" issues.

Rewrite configuration file operations

---

core/classes/Misc/HttpUtils.php
custom/languages/de_DE.json
custom/languages/en_UK.json
custom/languages/nl_NL.json

Fixes Cloudflare typo mentioned by @PadowYT2 in discord

Fix Cloudflare typo

---

core/classes/Core/Input.php

This PR will close #2866 and the fix has been confirmed by a user in the discord.

Fix subdirectory installation issues with TinyMCE

---

modules/Core/classes/Integrations/MinecraftIntegration.php
modules/Core/includes/endpoints/ServerInfoEndpoint.php

The plugin command is configurable, so the website should display the same command

Allow server to send correct verify command

---

core/classes/Core/Email.php

Opening a PR because I can't test these changes

Handle non-ascii characters in subject, SITE_NAME and message

---

modules/Core/pages/panel/index.php

This PR will likely resolve #2937 as it supports both the old and new mariadb version format

Match both old and new mariadb version format

---

core/classes/Core/Input.php
custom/panel_templates/Default/template.php
modules/Core/pages/panel/emails_mass_message.php
modules/Core/pages/panel/users_edit.php

Only show source code option in staffcp pages for TinyMCE

---

modules/Core/pages/oauth.php

Support 2FA with OAuth2 logging in

---

custom/languages/en_UK.json
modules/Core/pages/register.php

Block banned ips from registering

---

core/classes/Core/User.php
core/classes/Misc/Announcements.php
custom/languages/en_UK.json
modules/Discord Integration/hooks/DiscordFormatterHook.php

I added userGroupAdded and userGroupRemoved events to discord webhook formatter and fixed hardcoded New Announcement.

Add userGroupAdded and userGroupRemoved to discord webhook formatter

---

core/classes/DTO/UpdateCheck.php
modules/Core/pages/panel/update.php

Fix upgrade check to use direct upgrade zip link

---

core/includes/image_upload.php

Fix upload image error

---

core/templates/navbar.php
custom/languages/en_UK.json
custom/templates/DefaultRevamp/js/core/core.js
custom/templates/DefaultRevamp/navbar.tpl
custom/templates/DefaultRevamp/template.php
modules/Core/pages/logout.php

Logout rework

---

modules/Core/pages/panel/emails_errors.php

Fix exception when user id is null in email_error table

Fix exception when user id is null in email_error table
